version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: performance_test_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start.sh
    ports:
      - "8000:8000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: performance_test_production_postgres
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:3.0

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: performance_test_production_nginx
    volumes:
        - ./compose/local/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - django
    ports:
      - "0.0.0.0:8003:80"
